### ISSUE TITLE
Integration test of the docker feature is unstable

### ISSUE THREAD

**Issue by essobedo** [apache/camel-karaf#438]
The test fails with the next errors:
```
2024-07-17T09:22:06.3354618Z [INFO] Running org.apache.karaf.camel.itest.CamelDockerITest
2024-07-17T09:22:06.3646954Z SLF4J(W): Class path contains multiple SLF4J providers.
2024-07-17T09:22:06.3648747Z SLF4J(W): Found provider [org.ops4j.pax.logging.slf4j.PaxLoggingSLF4JServiceProvider@15d0c81b]
2024-07-17T09:22:06.3650682Z SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@6acdbdf5]
2024-07-17T09:22:06.3652563Z SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2024-07-17T09:22:06.3654176Z SLF4J(I): Actual provider is of type [org.ops4j.pax.logging.slf4j.PaxLoggingSLF4JServiceProvider@15d0c81b]
2024-07-17T09:22:11.9734708Z [org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck] WARN : An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, stderr=)
2024-07-17T09:22:13.1746580Z WARNING: package org.apache.karaf.specs.locator not in java.base
2024-07-17T09:22:19.8854140Z 
2024-07-17T09:22:19.8855123Z CamelDockerITest: testResultMock
2024-07-17T09:22:21.7906876Z bundle:list -s -t 0 | grep camel-docker-test
2024-07-17T09:22:42.6129249Z java.lang.AssertionError: mock://camel-docker-test Received message count. Expected: <3> but was: <0>
2024-07-17T09:22:42.6130190Z 
2024-07-17T09:22:42.6130396Z CamelDockerITest: testResultMock
2024-07-17T09:22:42.6131376Z 	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1975)
2024-07-17T09:22:42.6132727Z 	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1909)
2024-07-17T09:22:42.6134173Z 	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:454)
2024-07-17T09:22:42.6135673Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:432)
2024-07-17T09:22:42.6186728Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:422)
2024-07-17T09:22:42.6188240Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:218)
2024-07-17T09:22:42.6190322Z 	at org.apache.karaf.camel.itests.CamelSingleFeatureResultMockBasedRoute.assertMockEndpointsSatisfied(CamelSingleFeatureResultMockBasedRoute.java:26)
2024-07-17T09:22:42.6192672Z 	at org.apache.karaf.camel.itest.CamelDockerITest.testResultMock(CamelDockerITest.java:42)
2024-07-17T09:22:42.6194060Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:22:42.6195508Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:22:42.6197172Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:22:42.6198492Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:22:42.6199605Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2024-07-17T09:22:42.6200942Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-07-17T09:22:42.6202308Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2024-07-17T09:22:42.6203662Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-07-17T09:22:42.6204983Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-07-17T09:22:42.6206234Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-07-17T09:22:42.6207315Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
2024-07-17T09:22:42.6367978Z 	at org.apache.karaf.itests.KarafTestSupport$Retry$1.evaluate(KarafTestSupport.java:160)
2024-07-17T09:22:42.6369441Z 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2024-07-17T09:22:42.6371173Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runLeafWithRetry(ContainerTestRunner.java:97)
2024-07-17T09:22:42.6373194Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChildWithRetry(ContainerTestRunner.java:84)
2024-07-17T09:22:42.6375308Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:75)
2024-07-17T09:22:42.6377044Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:43)
2024-07-17T09:22:42.6378374Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2024-07-17T09:22:42.6379355Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2024-07-17T09:22:42.6380381Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2024-07-17T09:22:42.6381475Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2024-07-17T09:22:42.6382526Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2024-07-17T09:22:42.6383548Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2024-07-17T09:22:42.6384434Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2024-07-17T09:22:42.6385506Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2024-07-17T09:22:42.6386864Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.invokeViaJUnit(JUnitProbeInvoker.java:124)
2024-07-17T09:22:42.6388691Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:97)
2024-07-17T09:22:42.6390407Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
2024-07-17T09:22:42.6391878Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:22:42.6393436Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:22:42.6395208Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:22:42.6396777Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:22:42.6398199Z 	at org.ops4j.pax.exam.rbc.internal.RemoteBundleContextImpl.remoteCall(RemoteBundleContextImpl.java:85)
2024-07-17T09:22:42.6399736Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:22:42.6401264Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:22:42.6403200Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:22:42.6404634Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:22:42.6405753Z 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
2024-07-17T09:22:42.6406921Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
2024-07-17T09:22:42.6407924Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
2024-07-17T09:22:42.6409095Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
2024-07-17T09:22:42.6410365Z 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
2024-07-17T09:22:42.6411644Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
2024-07-17T09:22:42.6413092Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
2024-07-17T09:22:42.6414627Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
2024-07-17T09:22:42.6416111Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-07-17T09:22:42.6417519Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
2024-07-17T09:22:42.6419227Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-17T09:22:42.6420734Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-17T09:22:42.6421860Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-17T09:22:43.3180263Z bundle:list -s -t 0 | grep camel-docker-test
2024-07-17T09:23:03.5909318Z java.lang.AssertionError: mock://camel-docker-test Received message count. Expected: <3> but was: <0>
2024-07-17T09:23:03.5911826Z 	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1975)
2024-07-17T09:23:03.5915687Z 	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1909)
2024-07-17T09:23:03.5936673Z 	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:454)
2024-07-17T09:23:03.5938258Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:432)
2024-07-17T09:23:03.5939765Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:422)
2024-07-17T09:23:03.5941239Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:218)
2024-07-17T09:23:03.5943377Z 	at org.apache.karaf.camel.itests.CamelSingleFeatureResultMockBasedRoute.assertMockEndpointsSatisfied(CamelSingleFeatureResultMockBasedRoute.java:26)
2024-07-17T09:23:03.5945792Z 	at org.apache.karaf.camel.itest.CamelDockerITest.testResultMock(CamelDockerITest.java:42)
2024-07-17T09:23:03.5947215Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:23:03.5948720Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:23:03.5950440Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:23:03.5951800Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:23:03.5952933Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2024-07-17T09:23:03.5954393Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-07-17T09:23:03.5955799Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2024-07-17T09:23:03.5957429Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-07-17T09:23:03.5958801Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-07-17T09:23:03.5960073Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-07-17T09:23:03.5961298Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
2024-07-17T09:23:03.5962447Z 	at org.apache.karaf.itests.KarafTestSupport$Retry$1.evaluate(KarafTestSupport.java:160)
2024-07-17T09:23:03.5963554Z 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2024-07-17T09:23:03.5964940Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runLeafWithRetry(ContainerTestRunner.java:97)
2024-07-17T09:23:03.5966846Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChildWithRetry(ContainerTestRunner.java:84)
2024-07-17T09:23:03.5968684Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:75)
2024-07-17T09:23:03.5970416Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:43)
2024-07-17T09:23:03.5971758Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2024-07-17T09:23:03.5972714Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2024-07-17T09:23:03.5973761Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2024-07-17T09:23:03.5974811Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2024-07-17T09:23:03.5975826Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2024-07-17T09:23:03.5976806Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2024-07-17T09:23:03.5977979Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2024-07-17T09:23:03.5978749Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2024-07-17T09:23:03.5980026Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.invokeViaJUnit(JUnitProbeInvoker.java:124)
2024-07-17T09:23:03.5981823Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:97)
2024-07-17T09:23:03.5983467Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
2024-07-17T09:23:03.5985312Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:23:03.5986802Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:23:03.5988481Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:23:03.5989826Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:23:03.5993744Z 	at org.ops4j.pax.exam.rbc.internal.RemoteBundleContextImpl.remoteCall(RemoteBundleContextImpl.java:92)
2024-07-17T09:23:03.5995773Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:23:03.5997243Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:23:03.5998866Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:23:03.6000191Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:23:03.6001293Z 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
2024-07-17T09:23:03.6002413Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
2024-07-17T09:23:03.6003387Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
2024-07-17T09:23:03.6004550Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
2024-07-17T09:23:03.6005791Z 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
2024-07-17T09:23:03.6007030Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
2024-07-17T09:23:03.6008659Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
2024-07-17T09:23:03.6009974Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
2024-07-17T09:23:03.6011408Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-07-17T09:23:03.6012914Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
2024-07-17T09:23:03.6014389Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-17T09:23:03.6015866Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-17T09:23:03.6016946Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-17T09:23:05.0585648Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 58.72 s <<< FAILURE! -- in org.apache.karaf.camel.itest.CamelDockerITest
2024-07-17T09:23:05.0588158Z [ERROR] org.apache.karaf.camel.itest.CamelDockerITest.testResultMock -- Time elapsed: 43.80 s <<< FAILURE!
2024-07-17T09:23:05.0590032Z java.lang.AssertionError: mock://camel-docker-test Received message count. Expected: <3> but was: <0>
2024-07-17T09:23:05.0591594Z 	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1975)
2024-07-17T09:23:05.0593259Z 	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1909)
2024-07-17T09:23:05.0595036Z 	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:454)
2024-07-17T09:23:05.0596195Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:432)
2024-07-17T09:23:05.0597441Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:422)
2024-07-17T09:23:05.0599173Z 	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:218)
2024-07-17T09:23:05.0601483Z 	at org.apache.karaf.camel.itests.CamelSingleFeatureResultMockBasedRoute.assertMockEndpointsSatisfied(CamelSingleFeatureResultMockBasedRoute.java:26)
2024-07-17T09:23:05.0603560Z 	at org.apache.karaf.camel.itest.CamelDockerITest.testResultMock(CamelDockerITest.java:42)
2024-07-17T09:23:05.0604909Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:23:05.0606630Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:23:05.0608308Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:23:05.0609642Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:23:05.0610786Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2024-07-17T09:23:05.0612154Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-07-17T09:23:05.0613530Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2024-07-17T09:23:05.0614896Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-07-17T09:23:05.0616216Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-07-17T09:23:05.0617486Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-07-17T09:23:05.0618573Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
2024-07-17T09:23:05.0619703Z 	at org.apache.karaf.itests.KarafTestSupport$Retry$1.evaluate(KarafTestSupport.java:160)
2024-07-17T09:23:05.0620789Z 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2024-07-17T09:23:05.0622123Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runLeafWithRetry(ContainerTestRunner.java:97)
2024-07-17T09:23:05.0624005Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChildWithRetry(ContainerTestRunner.java:84)
2024-07-17T09:23:05.0626021Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:75)
2024-07-17T09:23:05.0627508Z 	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:43)
2024-07-17T09:23:05.0628301Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2024-07-17T09:23:05.0628877Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2024-07-17T09:23:05.0629482Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2024-07-17T09:23:05.0630182Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2024-07-17T09:23:05.0630785Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2024-07-17T09:23:05.0631352Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2024-07-17T09:23:05.0631857Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2024-07-17T09:23:05.0632335Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2024-07-17T09:23:05.0633102Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.invokeViaJUnit(JUnitProbeInvoker.java:124)
2024-07-17T09:23:05.0634126Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:97)
2024-07-17T09:23:05.0635076Z 	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
2024-07-17T09:23:05.0635906Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:23:05.0636751Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:23:05.0637725Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:23:05.0638547Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:23:05.0639311Z 	at org.ops4j.pax.exam.rbc.internal.RemoteBundleContextImpl.remoteCall(RemoteBundleContextImpl.java:92)
2024-07-17T09:23:05.0640299Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-17T09:23:05.0641133Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-07-17T09:23:05.0642101Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-17T09:23:05.0642872Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-07-17T09:23:05.0643578Z 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
2024-07-17T09:23:05.0644217Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
2024-07-17T09:23:05.0644778Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
2024-07-17T09:23:05.0645456Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
2024-07-17T09:23:05.0646163Z 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
2024-07-17T09:23:05.0646875Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
2024-07-17T09:23:05.0647672Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
2024-07-17T09:23:05.0648518Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
2024-07-17T09:23:05.0649339Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-07-17T09:23:05.0650126Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
2024-07-17T09:23:05.0650955Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-17T09:23:05.0651794Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-17T09:23:05.0652427Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-17T09:23:05.0652706Z 
2024-07-17T09:23:10.0576744Z [ERROR] Surefire is going to kill self fork JVM. The exit has elapsed 5 seconds after System.exit(0).
2024-07-17T09:23:10.3919241Z [INFO] 
2024-07-17T09:23:10.3919657Z [INFO] Results:
2024-07-17T09:23:10.3920065Z [INFO] 
2024-07-17T09:23:10.3920424Z [ERROR] Failures: 
2024-07-17T09:23:10.3922102Z [ERROR]   CamelDockerITest.testResultMock:42 mock://camel-docker-test Received message count. Expected: <3> but was: <0>
2024-07-17T09:23:10.3923250Z [INFO] 
2024-07-17T09:23:10.3923710Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by essobedo** [comment]
See https://github.com/apache/camel-karaf/actions/runs/9971345400/job/27552237020 for more details

cc @stataru8

**Comment by stataru8** [comment]
The memory while the test is running seems fine, at least on my machine.

**Comment by f2par0** [comment]
Failed again in  https://github.com/apache/camel-karaf/actions/runs/9980703694/job/27582717583?pr=440
This seems to be the common error between the 2 executions :
```
[org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck] WARN : An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, stderr=)
WARNING: package org.apache.karaf.specs.locator not in java.base
```

**Comment by essobedo** [comment]
I re-added the IT. I close the ticket for now as I could not reproduce it, if it happens again, we will have enough info to investigate
