### ISSUE TITLE
Cannot get the remote bundle context

### ISSUE THREAD

**Issue by essobedo** [apache/camel-karaf#450]
The build fails randomly with errors of following type which block the build for one hour
```
2024-07-19T12:10:39.2009493Z java.lang.RuntimeException: Cannot get the remote bundle context
2024-07-19T12:10:39.2010889Z 	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.getRemoteBundleContext(RemoteBundleContextClientImpl.java:261)
2024-07-19T12:10:39.2013224Z 	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.waitForState(RemoteBundleContextClientImpl.java:218)
2024-07-19T12:10:39.2015722Z 	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.waitForState(KarafTestContainer.java:728)
2024-07-19T12:10:39.2017454Z 	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.startKaraf(KarafTestContainer.java:304)
2024-07-19T12:10:39.2019081Z 	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.start(KarafTestContainer.java:191)
2024-07-19T12:10:39.2020834Z 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
2024-07-19T12:10:39.2022447Z 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
2024-07-19T12:10:39.2023964Z 	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
2024-07-19T12:10:39.2025229Z 	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
2024-07-19T12:10:39.2026674Z 	at org.apache.karaf.camel.itests.PaxExamWithExternalResource.run(PaxExamWithExternalResource.java:102)
2024-07-19T12:10:39.2028172Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
2024-07-19T12:10:39.2029578Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
2024-07-19T12:10:39.2031094Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
2024-07-19T12:10:39.2032472Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
2024-07-19T12:10:39.2033321Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2024-07-19T12:10:39.2034830Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2024-07-19T12:10:39.2039122Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2024-07-19T12:10:39.2040118Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2024-07-19T12:10:39.2041330Z Caused by: java.rmi.NotBoundException: 50e90d14-23e5-4437-8bc0-d0c4925dbf41
2024-07-19T12:10:39.2042359Z 	at java.rmi/sun.rmi.registry.RegistryImpl.lookup(RegistryImpl.java:237)
2024-07-19T12:10:39.2043478Z 	at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:133)
2024-07-19T12:10:39.2044649Z 	at java.rmi/sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:470)
2024-07-19T12:10:39.2045928Z 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:299)
2024-07-19T12:10:39.2046762Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
2024-07-19T12:10:39.2047555Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
2024-07-19T12:10:39.2048338Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
2024-07-19T12:10:39.2050177Z 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
2024-07-19T12:10:39.2051385Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
2024-07-19T12:10:39.2053406Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
2024-07-19T12:10:39.2054863Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
2024-07-19T12:10:39.2056459Z 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-07-19T12:10:39.2057583Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
2024-07-19T12:10:39.2059305Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-19T12:10:39.2060464Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-19T12:10:39.2061415Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-19T12:10:39.2062117Z 	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
2024-07-19T12:10:39.2063140Z 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
2024-07-19T12:10:39.2063820Z 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:381)
2024-07-19T12:10:39.2064953Z 	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:123)
2024-07-19T12:10:39.2066512Z 	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.getRemoteBundleContext(RemoteBundleContextClientImpl.java:248)
2024-07-19T12:10:39.2068009Z 	... 17 more
2024-07-19T12:10:39.2068251Z 
2024-07-19T12:10:39.2069025Z [ERROR] org.apache.karaf.camel.itest.CamelMailITest -- Time elapsed: 3608 s <<< ERROR!
2024-07-19T12:10:39.2070135Z java.lang.RuntimeException: Container never came up
2024-07-19T12:10:39.2071400Z 	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.stop(KarafTestContainer.java:695)
2024-07-19T12:10:39.2073347Z 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.tearDown(EagerSingleStagedReactor.java:118)
2024-07-19T12:10:39.2075166Z 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.afterClass(EagerSingleStagedReactor.java:132)
2024-07-19T12:10:39.2076773Z 	at org.ops4j.pax.exam.spi.reactors.ReactorManager.afterClass(ReactorManager.java:441)
2024-07-19T12:10:39.2078056Z 	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:107)
2024-07-19T12:10:39.2079548Z 	at org.apache.karaf.camel.itests.PaxExamWithExternalResource.run(PaxExamWithExternalResource.java:102)
2024-07-19T12:10:39.2081137Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
2024-07-19T12:10:39.2082615Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
2024-07-19T12:10:39.2084203Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
2024-07-19T12:10:39.2085855Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
2024-07-19T12:10:39.2087401Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2024-07-19T12:10:39.2088928Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2024-07-19T12:10:39.2090245Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
```

**Comment by jbonofre** [comment]
That's probably due to a refresh or timeout when the Karaf container starts. When refresh happens, the ref to the context change and so the context handler points to invalid bundle context. Let me take a look. Same can happen if the container never comes up.

**Comment by essobedo** [comment]
Doesn't seem to occur anymore, moreover, it only happened on failing tests only so I'm closing it as it is only a side effect
