### ISSUE TITLE
LevelDB fails on Mac with Apple chip

### ISSUE THREAD

**Issue by essobedo** [apache/camel-karaf#495]
When launching the test on my mac I get the next error:
```
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
        Unable to resolve org.fusesource.leveldbjni.leveldbjni-all [163](R 163.0): missing requirement [org.fusesource.leveldbjni.leveldbjni-all [163](R 163.0)] osgi.native; (|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))) Unresolved requirements: [[org.fusesource.leveldbjni.leveldbjni-all [163](R 163.0)] osgi.native; (|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64)))]
        Unable to resolve camel-leveldb [159](R 159.0): missing requirement [camel-leveldb [159](R 159.0)] osgi.wiring.package; (&(osgi.wiring.package=org.iq80.leveldb)(version>=0.6.0)(!(version>=1.0.0))) [caused by: Unable to resolve org.fusesource.leveldbjni.leveldbjni-all [163](R 163.0): missing requirement [org.fusesource.leveldbjni.leveldbjni-all [163](R 163.0)] osgi.native; (|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64)))] Unresolved requirements: [[camel-leveldb [159](R 159.0)] osgi.wiring.package; (&(osgi.wiring.package=org.iq80.leveldb)(version>=0.6.0)(!(version>=1.0.0)))]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1049)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by jbonofre** [comment]
Yes, that's a known issue as leveldbjni is x86 arch only.

I have a workaround in mind, I will fix that.

**Comment by essobedo** [comment]
Looking at the issue more closely, it seems that the [underlying library](https://github.com/fusesource/leveldbjni) is no longer maintained for more than 7 years so clearly there is no support for ARM64, so I will rather skip this test for this architecture
