### ISSUE TITLE
feature & camel 4.7

### ISSUE THREAD

**Issue by mikadev** [apache/camel-karaf#502]
``with k4.4.6 when i try to use feature:

` <feature>camel-jackson</feature>`

I got this one 
```
karaf@root()> feature:install my-feature
org.apache.felix.resolver.reason.ReasonException: Unable to resolve camel-jackson/4.7.0: missing requirement [camel-jackson/4.7.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.databind)(version>=2.17.0)(!(version>=3.0.0)))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:462)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
```
I think this is related to bundle start level (maybe not) for sure if i just run feature-install camel-jackson it work

**Comment by mikadev** [comment]
More weird 

After successfully install running `feature:install camel-jackson` if i run again i got again:
```
karaf@root()> feature:install camel-jackson
org.apache.felix.resolver.reason.ReasonException: Unable to resolve camel-jackson/4.7.0: missing requirement [camel-jackson/4.7.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.databind)(version>=2.17.0)(!(version>=3.0.0)))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:462)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:256)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Error executing command: Unable to resolve camel-jackson/4.7.0: missing requirement [camel-jackson/4.7.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.databind)(version>=2.17.0)(!(version>=3.0.0)))"
```

**Comment by stataru8** [comment]
I did some tests with the `camel-jackson` feature, and it appears to be functioning properly on my side. 

Is it possible to share the output of `feature:info my-feature`?

The error you're seeing is because some bundle is not finding the package `com.fasterxml.jackson.databind` with `version >=2.17.0` and `version < 3.0.0`. Could you also share the full error log message? (might help find out the problematic bundle)

After executing `feature:install camel-jackson`, what is the output of `list -t 0 -u | grep jackson` ?

**Comment by stataru8** [comment]
Do you have the `camel-karaf` repository declared in the features file that `my-feature` comes from?
```
<features name="test-features" xmlns="http://karaf.apache.org/xmlns/features/v1.4.0">

    <!-- Apache Camel Karaf features repository -->
    <repository>mvn:org.apache.camel.karaf/apache-camel/4.7.0/xml/features</repository>
	
    <!-- Camel Jackson feature -->
    <feature name="my-feature" version="4.7.0">
        <feature version="4.7.0">camel-jackson</feature>
    </feature>

</features>
```

**Comment by mikadev** [comment]
Hello @stataru8 
`list -t 0 -u | grep jackson`
```
128 x Active   x  80 x 2.17.1             x mvn:com.fasterxml.jackson.core/jackson-annotations/2.17.1
129 x Active   x  80 x 2.17.1             x wrap:mvn:com.fasterxml.jackson.core/jackson-core/2.17.1$overwrite=merge&Bundle-Version=2.17.1&SPI-Provider=*
130 x Active   x  80 x 2.17.1             x mvn:com.fasterxml.jackson.core/jackson-databind/2.17.1
247 x Active   x  50 x 4.7.0              x mvn:org.apache.camel.karaf/camel-jackson/4.7.0
```

No i wasn't have `camel-karaf` in my feature (i add it but still the same)

**Comment by stataru8** [comment]
Hello, thank you for providing the additional information.

In the error logs, I'm seeing 3 different errors, in the following order
- failed to install `com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.17.1` because `mvn` is missing
- failed to install `mvn:com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.17.1`, because `com.fasterxml.jackson.core` is missing. Before getting this one, did you had the feature `camel-jackson` installed? The output of `list -t 0 -u | grep jackson` you shared is the expected one if `camel-jackson` was installed. 
- failed to install `mvn:com.fasterxml.jackson.datatype/jackson-core/2.17.1` because the maven artifact doesn't exist.


I've tried to install the following feature, and it worked fine, all the jackson bundles could get into the **Active** state.
```
<feature name="my-feature">
   <feature version="4.7.0">camel</feature>
   <feature>camel-blueprint</feature>
   <feature>camel-jackson</feature>
   <feature>camel-jsonpath</feature>
   <feature>camel-jms</feature>
   <feature>camel-http</feature>
   <feature>camel-sql</feature>
   <feature>camel-freemarker</feature>
        
   <bundle>mvn:com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.17.1</bundle>
   <bundle>mvn:com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.17.1</bundle>
   <bundle>mvn:org.apache.commons/commons-lang3/3.14.0</bundle>
</feature>
```
```
karaf@root()> list -t 0 -u | grep jackson
 90 | Active   |  50 | 4.7.0              | mvn:org.apache.camel.karaf/camel-jackson/4.7.0
120 | Active   |  80 | 2.17.1             | mvn:com.fasterxml.jackson.core/jackson-annotations/2.17.1
121 | Active   |  80 | 2.17.1             | wrap:mvn:com.fasterxml.jackson.core/jackson-core/2.17.1$overwrite=merge&Bundle-Version=2.17.1&SPI-Provider=*
122 | Active   |  80 | 2.17.1             | mvn:com.fasterxml.jackson.core/jackson-databind/2.17.1
123 | Active   |  80 | 2.17.1             | mvn:com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.17.1
124 | Active   |  80 | 2.17.1             | mvn:com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.17.1
```

I’m not sure about the contents of the other features above the `camel` ones, so it’s possible that one of them includes
`<bundle>mvn:com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.17.1</bundle>` but is missing the other required Jackson bundles. I think it’s safe to change the order of the features and declare the camel features first.

**Comment by mikadev** [comment]
Yeah yeah you are right it was conflict with one of my other bundle thanks for the help
