### ISSUE TITLE
camel debezium

### ISSUE THREAD

**Issue by mikadev** [apache/camel-karaf#546]
Hello maybe it's just me but whit latest Karaf (fresh install) i just install latest camel (4.8.1) when i do:

feature:install camel-debezium-mysql all my ram is eating nothing happen no log just freeze my laptop

**Comment by mikadev** [comment]
At the end after restarting karaf i just got this one

```
Status: Failure
Camel Blueprint
Camel context "dt-integ-cdc"
Exception: No implementation of Debezium engine builder was found
io.debezium.DebeziumException: No implementation of Debezium engine builder was found
        at io.debezium.engine.DebeziumEngine.determineBuilderFactory(DebeziumEngine.java:341)
        at io.debezium.engine.DebeziumEngine.create(DebeziumEngine.java:311)
        at io.debezium.engine.DebeziumEngine.create(DebeziumEngine.java:286)
        at io.debezium.engine.DebeziumEngine.create(DebeziumEngine.java:272)
        at org.apache.camel.component.debezium.DebeziumConsumer.createDbzEngine(DebeziumConsumer.java:72)
        at org.apache.camel.component.debezium.DebeziumConsumer.doStart(DebeziumConsumer.java:52)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:123)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:126)
        at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3212)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:428)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:344)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:222)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:132)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2898)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2528)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2483)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:123)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2087)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:211)
        at org.apache.camel.blueprint.BlueprintCamelContext.start(BlueprintCamelContext.java:234)
        at org.apache.camel.blueprint.BlueprintCamelContext.maybeStart(BlueprintCamelContext.java:276)
        at org.apache.camel.blueprint.BlueprintCamelContext.blueprintEvent(BlueprintCamelContext.java:180)
        at org.apache.aries.blueprint.container.BlueprintEventDispatcher$3.call(BlueprintEventDispatcher.java:197)
        at org.apache.aries.blueprint.container.BlueprintEventDispatcher$3.call(BlueprintEventDispatcher.java:195)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mikadev** [comment]
Maybe it will work one day i churn

**Comment by jbonofre** [comment]
@mikadev @essobedo pushed fixes about camel-debezium for camel-karaf 4.8.1 and the itests worked.
Can you please provide the list of features alreeady install when you install camel-debezium ?
Do you import kafka packages in your dt-integ-cdc bundle ?

**Comment by mikadev** [comment]
![image](https://github.com/user-attachments/assets/ddd83c71-6031-4c7a-a325-c128841b3a25)
```
 <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>5.1.9</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Import-Package>*</Import-Package>
                        <Export-Package/>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-debezium-mysql</artifactId>
            <version>${camel.version}</version>
            <scope>provided</scope>
        </dependency>
  </dependencies>

```

**Comment by essobedo** [comment]
We can try to improve it a bit more, but it should not be too hard to fix it on your side by adding a dynamic import of type `org.apache.kafka.connect*`. 

As a reminder, it is an open-source project, so feel free to propose PRs to improve it, we will be happy to review them

**Comment by jbonofre** [comment]
@mikadev when you use `*` for `Import-Package`, bnd will actually import only the clearly state packages, not necessarily the transitive.
In your case, check the `MANIFEST` to see if kafka packages are there and if not (as I guess), "force" the import by defining the FQN. Something like:

```
<Import-Package>
   org.apache.kafka.connect,
   org.apache.kafka,
   *
</Import-Package>
```

**Comment by mikadev** [comment]
Many thanks for the help :) 

'not necessarily the transitive.' this is unclear for me in some case transitive are yes imported no ?

**Comment by mikadev** [comment]
Hello even by adding Import i have the same error any idea ?

**Comment by essobedo** [comment]
@mikadev Try to add `<DynamicImport-Package>org.apache.kafka.connect.*,io.debezium.*,com.mysql.cj.jdbc</DynamicImport-Package>` to the configuration of the `maven-bundle-plugin`

**Comment by essobedo** [comment]
Closing it as we provided information to fix the problem on your side, feel free to re-open it if it did not work

**Comment by mikadev** [comment]
> Closing it as we provided information to fix the problem on your side, feel free to re-open it if it did not work

Ok i'll try asap thanks
