### ISSUE TITLE
CxfRsBlueprintEndpointFactoryBean class not found issue

### ISSUE THREAD

**Issue by prasadfrommori** [apache/camel-karaf#548]
Hi Team

I am working with Camel upgrade from 3.14.0 to 4.7.0. now issue occurs with camel-cxf-rest 4.7.0 with karaf 4.4.6. while deploying the camel is trying to expose a cxf service which is having dependency issue( camel-cxf-rest is looking) with the class org.apache.camel.component.cxf.**jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean** but the camel-cxf-blueprint contains org.apache.camel.component.cxf.**blueprint.jaxrs.CxfRsBlueprintEndpointFactoryBean**.

Error:
2024-11-06T12:15:07,742 | ERROR | Blueprint Event Dispatcher: 1 | BlueprintCamelContext            | 280 - camel-blueprint - 4.7.0 | Error occurred during starting CamelContext: TestCamelContext
org.apache.camel.FailedToCreateRouteException: Failed to create route bulk: Route(bulk)[From[cxfrs:bean:bulk?bindingStyle=SimpleConsumer... because of Failed to resolve endpoint: cxfrs://bean:bulk?bindingStyle=SimpleConsumer due to: org.apache.camel.component.cxf.jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:92) ~[!/:?]
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49) ~[!/:?]
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:720) ~[!/:?]
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:587) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2390) ~[!/:?]
	at org.apache.camel.support.service.BaseService.init(BaseService.java:78) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2024) ~[!/:?]
	at org.apache.camel.support.service.BaseService.start(BaseService.java:105) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2043) ~[!/:?]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:211) ~[!/:?]
	at org.apache.camel.blueprint.BlueprintCamelContext.start(BlueprintCamelContext.java:234) ~[!/:?]
	at org.apache.camel.blueprint.BlueprintCamelContext.maybeStart(BlueprintCamelContext.java:276) ~[!/:?]
	at org.apache.camel.blueprint.BlueprintCamelContext.blueprintEvent(BlueprintCamelContext.java:180) [!/:?]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher$3.call(BlueprintEventDispatcher.java:197) [!/:1.10.3]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher$3.call(BlueprintEventDispatcher.java:195) [!/:1.10.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: cxfrs://bean:bulk?bindingStyle=SimpleConsumer due to: org.apache.camel.component.cxf.jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:835) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:735) ~[!/:?]
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:66) ~[!/:?]
	at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:199) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:106) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:86) ~[!/:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.component.cxf.jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean
	at org.apache.camel.impl.engine.DefaultClassResolver.resolveMandatoryClass(DefaultClassResolver.java:134) ~[?:?]
	at org.apache.camel.component.cxf.jaxrs.CxfRsComponent.createSpringContextEndpoint(CxfRsComponent.java:120) ~[?:?]
	at org.apache.camel.component.cxf.jaxrs.CxfRsComponent.doCreateEndpoint(CxfRsComponent.java:97) ~[?:?]
	at org.apache.camel.component.cxf.jaxrs.CxfRsComponent.createEndpoint(CxfRsComponent.java:65) ~[?:?]
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:801) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:735) ~[!/:?]
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:66) ~[!/:?]
	at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:199) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:106) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:86) ~[!/:?]
	... 23 more

Class location:
![image](https://github.com/user-attachments/assets/2b323111-eb8c-429d-9072-fe31bd95ba56)

Reference of source code:
Lone no 121
https://github.com/apache/camel/blob/camel-4.7.0/components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsComponent.java

**Comment by essobedo** [comment]
Could you please provide steps to reproduce? Have you tried with version 4.8.1?

**Comment by essobedo** [comment]
Please note that v 4.7 is not an LTS, so no patch versions will be released

**Comment by prasadfrommori** [comment]
I will check with  4.8.1 and come back. but i can see same code issue is there.

**Comment by prasadfrommori** [comment]
Hi @essobedo 

I have tested with latest version of camel 4.8.1 still same issue

Error occurred during starting CamelContext: NIP-Framework-Context
org.apache.camel.FailedToCreateRouteException: Failed to create route bulk: Route(bulk)[From[cxfrs:bean:bulk?bindingStyle=SimpleConsumer... because of Failed to resolve endpoint: cxfrs://bean:bulk?bindingStyle=SimpleConsumer due to: org.apache.camel.component.cxf.jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:92) ~[!/:?]
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49) ~[!/:?]
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:726) ~[!/:?]
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:592) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2433) ~[!/:?]
	at org.apache.camel.support.service.BaseService.init(BaseService.java:85) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2068) ~[!/:?]
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2087) ~[!/:?]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:211) ~[!/:?]
	at org.apache.camel.blueprint.BlueprintCamelContext.start(BlueprintCamelContext.java:234) ~[!/:?]
	at org.apache.camel.blueprint.BlueprintCamelContext.maybeStart(BlueprintCamelContext.java:276) ~[!/:?]
	at org.apache.camel.blueprint.BlueprintCamelContext.blueprintEvent(BlueprintCamelContext.java:180) [!/:?]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher$3.call(BlueprintEventDispatcher.java:197) [!/:1.10.3]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher$3.call(BlueprintEventDispatcher.java:195) [!/:1.10.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: cxfrs://bean:bulk?bindingStyle=SimpleConsumer due to: org.apache.camel.component.cxf.jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:839) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:739) ~[!/:?]
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:66) ~[!/:?]
	at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:199) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:106) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:86) ~[!/:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.component.cxf.jaxrs.blueprint.CxfRsBlueprintEndpointFactoryBean
	at org.apache.camel.impl.engine.DefaultClassResolver.resolveMandatoryClass(DefaultClassResolver.java:134) ~[?:?]
	at org.apache.camel.component.cxf.jaxrs.CxfRsComponent.createSpringContextEndpoint(CxfRsComponent.java:124) ~[?:?]
	at org.apache.camel.component.cxf.jaxrs.CxfRsComponent.doCreateEndpoint(CxfRsComponent.java:101) ~[?:?]
	at org.apache.camel.component.cxf.jaxrs.CxfRsComponent.createEndpoint(CxfRsComponent.java:68) ~[?:?]
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:805) ~[!/:?]
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:739) ~[!/:?]
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:66) ~[!/:?]
	at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:199) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:106) ~[!/:?]
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:86) ~[!/:?]
	... 23 more
2024-11-19T10:32:04,168 | DEBUG | fileinstall-D:\FA\Product\Common_Utils\selenium\apache-karaf-4.4.6/deploy | BlueprintContainerImpl           | 162 - org.apache.aries.blueprint.core - 1.10.3 | Running container for blueprint bundle com.ndfs.nip.framework.nip-framework/2.10.9 in state Created

**Comment by prasadfrommori** [comment]
Tested with: 
jdk-17.0.10
Maven 3.9.6

1) Exposed a service using blueprint + Camel 4.8.1 + Camel Cxf as packaged in the attachement 
2) Deploy in apache karaf where packaged bundle.

In karaf log we will see Error. 

Code attached for the testing 

[Dummy.zip](https://github.com/user-attachments/files/17811878/Dummy.zip)

**Comment by essobedo** [comment]
Hi, thanks for the steps to reproduce; however, we cannot accept zip files for security reasons. Could you please provide the files in a github repository instead?

**Comment by prasadfrommori** [comment]
@essobedo : Please find the required git hub link 

https://github.com/prasadfrommori/CamelCxfIssue

**Comment by essobedo** [comment]
Perfect, thank you. I will try to check that tomorrow, meanwhile don't hesitate to check the integration test we have https://github.com/apache/camel-karaf/tree/main/tests/features/camel-cxf to identify what's wrong in your case

**Comment by essobedo** [comment]
I could reproduce and I understand the bug, thx for reporting. I will propose a fix ASAP

**Comment by jbonofre** [comment]
Sorry I was traveling and I didn't have time to reply. I will take a look as well.

**Comment by prasadfrommori** [comment]
> I could reproduce and I understand the bug, thx for reporting. I will propose a fix ASAP

Thank You

**Comment by prasadfrommori** [comment]
Hi @essobedo, 

Hope you are good. Can you help me with time line ?

**Comment by jbonofre** [comment]
@prasadfrommori I should have time to investigate and provide a fix today.

**Comment by prasadfrommori** [comment]
Hi @jbonofre 

I understand your busy day. is it possible to provide some update today ?

**Comment by prasadfrommori** [comment]
@essobedo : thanks for the fixes. 
when the 4.8.2/4.9.0 will be published?

**Comment by essobedo** [comment]
There is a last issue to fix (https://github.com/apache/camel-karaf/issues/562) before the release.

**Comment by prasadfrommori** [comment]
@essobedo : Hope you are doing well.  
When will this fix be released?

**Comment by essobedo** [comment]
It is in progress
